kumano_shift_maker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('kumano_shift_maker/',include('shift_maker.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shift_maker/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from django.views.generic import TemplateView


app_name = 'shift_maker'
urlpatterns = [
    path('mypage/',views.MyPageView.as_view(),name='mypage'),
    path('mypage/recruitment/<int:pk>/',views.shift_recruit_view,name='recruit'),
    path('mypage/recruitment/<int:pk>/answer/',views.shift_receive_answer_view,name='answer'),
    path('mypage/recruit/<int:pk>/', views.shift_recruit_detail,name='recruit_detail'),
    path('mypage/recruit/<int:pk>/calculate/',views.shift_calculate,name='scheduling'),
    path('mypage/recruit/<int:pk>/calculate/result',views.shift_calculate_result,name='result_schedule'),
    path('mypage/memberlist/',views.BlockMemberList.as_view(),name='memberlist'),
    path('mypage/contentlist/',views.WorkContentList.as_view(),name='contentlist'),
    path('mypage/contentlist/assign/<int:pk>/',views.assign_content,name='assign_content'),
    path('mypage/createpage/',TemplateView.as_view(template_name='shift_maker/createpage.html'),name='create_page'),
    path('mypage/createpage/createslot/',views.CreateSlot.as_view(),name='createslot'),
    path('mypage/createpage/createshift/',views.CreateShift.as_view(),name='createshift'),
    path('mypage/createpage/createtemplate/',views.CreateShiftTemplate.as_view(),name='createshifttemplate'),
    path('mypage/createpage/shifttempform/',views.ShiftFormFromTemplateView.as_view(),name='shift_create_form_template'),
    path('mypage/shifttempform/creshiftfromtemp/',views.shift_from_template,name='shift_from_template'),
    path('mypage/assign_lack/<int:pk>/assign/',views.assign_lack_slot,name='assign_lack'),
    path('mypage/assign_slot/<int:pk>/assign/',views.assign_slot,name='assign'),
    path('mypage/replace/<int:slot_id>/<int:user_id>/',views.replace_slot,name='replace'),
    path('mypage/delete/<int:pk>/delete/',views.delete_assigned_slot,name='slot_delete'),
    path('mypage/delete_booking/<int:pk>/delete/',views.delete_booking_slot,name='booking_slot_delete'),
    path('login/', LoginView.as_view(template_name='admin/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
]

shift_maker/forms.py
from django import forms
from .models import Shift, ShiftTemplate, Block
from django.contrib.auth.forms import PasswordChangeForm

class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

#シフト回答フォーム
class ShiftForm(forms.ModelForm):
    class Meta():
        model=Shift
        fields=('slot',)
#シフト表のテンプレートからシフト表を作るフォーム           
class ShiftFormFromTemplate(forms.Form):
    shift_template=forms.ModelChoiceField(queryset=ShiftTemplate.objects.all())
    first_day=forms.DateField(label="シフト初日の日付",widget=forms.DateInput(attrs={"type":"date"}))
    shift_name=forms.CharField(max_length=40,label="シフト名")
    deadline=forms.DateField(label="シフト募集締切日",widget=forms.DateInput(attrs={"type":"date"}))
    target=forms.ChoiceField(required=True,choices=Block.choices,label="対象ブロック")


shift_maker/views.py
from dataclasses import fields
from string import Template
from urllib import request
from django import forms
from django.http import HttpResponseRedirect
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls.base import reverse_lazy
from django.views.generic import (
    CreateView,
    FormView,
    TemplateView,
    ListView,
    UpdateView,
)
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.db.models import Count, F
from django.views.generic.detail import DetailView
from .models import Slot, Shift, User, ShiftTemplate, WorkContent
from .forms import ShiftForm, ShiftFormFromTemplate, MyPasswordChangeForm
from datetime import timedelta
import pandas as pd
import numpy as np
from ortoolpy.etc import addvar
from pulp import *
from ortoolpy import addvars, addbinvars
from django_pandas.io import read_frame
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
# 回答フォームのビュー
@login_required
def shift_recruit_view(request, pk):
    shift = get_object_or_404(Shift, pk=pk)
    if shift.is_decided:
        return HttpResponseRedirect(reverse("shift_maker:result_schedule", args=[shift.pk]))
    forms = ShiftForm(request.POST or None, instance=shift)
    if forms.is_valid():
        forms.save()
    days_list = sorted(list(set(list(shift.slot.all().values_list("day", flat=True)))))
    time_list = sorted(
        list(set(list(shift.slot.all().values_list("start_time", "end_time"))))
    )
    sametime_slotlist = []
    for start_time, end_time in time_list:
        time_slot_list = []
        for day in days_list:
            slots = shift.slot.filter(day=day, start_time=start_time, end_time=end_time)
            time_slot_list.append(slots)
        sametime_slotlist.append((start_time, end_time, time_slot_list))
    return render(
        request,
        "shift_maker/answer.html",
        {
            "forms": forms,
            "shift": shift,
            "days_list": days_list,
            "sametime_slot_list": sametime_slotlist,
        },
    )


# 回答処理用の関数
def shift_receive_answer_view(request, pk):
    user = request.user
    answer = request.POST.getlist("slot")
    testslots = user.assigning_slot.all()
    for answer_slot_id in answer:
        slot = Slot.objects.get(id=answer_slot_id)
        user.assigning_slot.add(slot)
        user.save()
    for slot in testslots:
        print(slot.workname)
    return HttpResponseRedirect(reverse("shift_maker:mypage"))


def shift_recruit_detail(request, pk):
    shift = get_object_or_404(Shift, pk=pk)
    days_list = sorted(list(set(list(shift.slot.all().values_list("day", flat=True)))))
    time_list = sorted(
        list(set(list(shift.slot.all().values_list("start_time", "end_time"))))
    )
    sametime_slotlist = []
    for start_time, end_time in time_list:
        time_slot_list = []
        for day in days_list:
            slots = shift.slot.filter(day=day, start_time=start_time, end_time=end_time)
            one_table = []
            for slot in slots:
                one_table.append((slot, slot.slot_users.all()))
            time_slot_list.append(one_table)
        sametime_slotlist.append((start_time, end_time, time_slot_list))
    return render(
        request,
        "shift_maker/recruit_detail.html",
        {
            "shift": shift,
            "days_list": days_list,
            "sametime_slot_list": sametime_slotlist,
        },
    )


class CreateSlot(CreateView):
    model = Slot
    fields = "__all__"
    success_url = reverse_lazy("shift_maker:mypage")


class CreateShiftTemplate(CreateView):
    model = ShiftTemplate
    fields = "__all__"

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super().form_valid(form)


class CreateShift(CreateView):
    model = Shift
    fields = ["shift_name", "first_day", "deadline", "slot", "target"]
    success_url = reverse_lazy("shift_maker:mypage")

    def form_valid(self, form):
        object = form.save(commit=False)
        object.creater = self.request.user
        object.save()
        Slot.objects.filter(day__lt=datetime.datetime.today()).delete()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"].fields["slot"].queryset = Slot.objects.filter(
            for_template=False
        )
        return context


class UserUpdate(UpdateView):
    template_name = "shift_maker/member_update_form.html"
    model = User
    fields = ["Block_name", "room_number", "password"]

    def get_success_url(self):
        return reverse("shift_maker:mypage")

    def get_form(self):
        form = super(UserUpdate, self).get_form()
        form.fields["Block_name"].label = "ブロック名"
        form.fields["room_number"].label = "部屋番号"
        form.fields["password"].label = "パスワード"
        return form


class PasswordChange(PasswordChangeView):
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy("shift_maker:password_change_done")
    template_name = "shift_maker/password_change.html"


class PasswordChangeDone(PasswordChangeDoneView):
    template_name = "shift_maker/password_change_done.html"


class ShiftFormFromTemplateView(FormView):
    template_name = "shift_maker/templateconvert.html"
    form_class = ShiftFormFromTemplate
    success_url = reverse_lazy("shift_maker:mypage")

    def form_valid(self, form):
        Slot.object.filter(day__lt=datetime.datetime.today()).delete()
        return super().form_valid(form)


# 計算しても加算されない
class MyPageView(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "shift_maker/mypage.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["decided_assign_slot"] = self.request.user.assigning_slot.filter(
            is_decided=True
        )
        context["undecided_assign_slot"] = self.request.user.assigning_slot.filter(
            is_decided=False
        )
        context["lack_slot"] = Slot.objects.annotate(
            assigning_number=Count("slot_users")
        ).filter(assigning_number__lt=F("required_number"), is_decided=True)
        context["shifts"] = Shift.objects.filter(is_decided=False)
        context["decided_shifts"] = Shift.objects.filter(is_decided=True)
        context["made_shifts"] = Shift.objects.filter(
            creater=self.request.user, is_decided=False
        )
        context["others_shifts"]=Shift.objects.exclude(creater=self.request.user,is_decided=True)
        return context


class BlockMemberList(ListView):
    model = User

    def get_queryset(self):
        return (
            User.objects.filter(Block_name=self.request.user.Block_name)
            .order_by("-workload_sum")
            .all()
        )


class WorkContentList(ListView):
    model = WorkContent


# シフトのテンプレートからShiftModelを作る関数
# TODO 不正なフォームへの対応
def shift_from_template(request):
    form = ShiftFormFromTemplate(data=request.POST)
    if request.method == "POST":
        if form.is_valid():
            selected_shift_template = form.cleaned_data.get("shift_template")
            slots = selected_shift_template.slot_templates.all()
            first_day = form.cleaned_data.get("first_day")
            shift_name = form.cleaned_data.get("shift_name")
            deadline = form.cleaned_data.get("deadline")
            target = form.cleaned_data.get("target")
            creater = request.user
            shift = Shift.objects.create(
                shift_name=shift_name,
                first_day=first_day,
                deadline=deadline,
                target=target,
                creater=creater,
            )
            for slot in slots:
                slot.day = first_day + timedelta(days=slot.days_from_start)
                slot.id = None
                slot.save()
                slot.workname = slot.workname + "(" + str(slot.id) + ")"
                slot.is_decided = False
                slot.save()
                shift.slot.add(slot)
            messages.success(request, "作成成功", fail_silently=True)
            return HttpResponseRedirect(reverse("shift_maker:mypage"))
        elif request.method == "GET":
            messages.error(request, "不正なフォームです", fail_silently=True)
            return HttpResponseRedirect(
                reverse("shift_maker:shift_create_form_template")
            )
        else:
            messages.error(request, "不正なフォームです", fail_silently=True)
            return HttpResponseRedirect(
                reverse("shift_maker:shift_create_form_template")
            )
    else:
        messages.error(request, "不正なフォームです", fail_silently=True)
        return HttpResponseRedirect(reverse("shift_maker:shift_create_form_template"))


# 制約条件ごとのテストは完了
def shift_calculate(request, pk):
    shift = get_object_or_404(Shift, pk=pk)
    # モデルインスタンスのフィールドの値をvalues_list で取り出してそれをlist()でlist化して
    # Pandasの列又は行に追加している
    # values_list で値を取り出した際の順序がどのようになっているのかわかっていないので順序が
    # おかしくなっている可能性あり
    slots = shift.slot.all()
    slot_df = read_frame(
        slots,
        fieldnames=["required_number", "content__workload", "content__id"],
        index_col="id",
    )
    print(slot_df)
    users = User.objects.filter(Block_name=shift.target)
    users_df = read_frame(users, fieldnames=["workload_sum"], index_col="id")
    user_ids = users.values_list("id", flat=True)
    user_list = list(user_ids)
    df = pd.DataFrame(index=slot_df.index, columns=user_list)
    df.fillna(0, inplace=True)
    workcontents = []
    for slot in slots:
        workcontents.append(slot.content.id)
        assigning_workers = slot.slot_users.all()

shift_maker/templates/shift_maker/answer.html
{% extends 'shift_maker/base.html' %}
{% block body-contents %}
<form action="{% url 'shift_maker:answer' shift.id %}" method="post">
{% csrf_token %}
<fieldset>
    <table class="table">
        <tr>
            <th>時間</th>
            {% for day in days_list %}
                <th>{{day|date:"n月j日"}}</th>
            {% endfor %}
        </tr>
        {% for start_time, end_time, time_slot_list in sametime_slot_list %}
        <tr>
            <td>{{ start_time|date:"G時i分" }}～{{ end_time|date:"G時i分" }}</td>
            {% for slots in time_slot_list %}
            {% if not slots %}
            <td>なし</td>
            {% else %}
            {% for slot in slots %}
                <td> <input type="checkbox" name="slot" id="slot{{ slot.id }}" value="{{ slot.id }}">
                    <label for="slot{{ slot.id }}" >{{ slot.workname }}</label><br></td>
            {% endfor %}
            {% endif %}

            {% endfor %}
        </tr>
        {% endfor %}
    </table>
</fieldset>
<input type="submit" value="回答">
</form>
{% endblock %}

shift_maker/templates/shift_maker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja" class="h-100">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>  
</head>

  <body style="padding-top: 60px;"> 
  <header>
    <!-- トップ固定ナビゲーション -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" 
      data-target="#navbar-header" aria-controls="navbar-header" 
      aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-header">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'shift_maker:mypage'%}">ホーム <span class="sr-only">(現位置)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" 
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">ドロップダウン</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'shift_maker:logout' %}">ログアウト</a>
              <a class="dropdown-item" href="{% url 'shift_maker:memberlist' %}">同ブロックの人たち</a>
              <a class="dropdown-item" href="{% url 'shift_maker:contentlist' %}">仕事内容一覧</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% if messages %}
    <ul class="messages_ul">
      {% for message in messages %}
        <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  </header>

  <main role="main" class="container">
    
    {% block body-contents %}
    {% endblock %}
  </main>
  
  {% block extrajs %}{% endblock %}

</body>
{% block modal %}{% endblock %}

<footer>
  {% block footer %}
  <a href="{% url 'shift_maker:logout' %}">ログアウト</a>
  {% endblock %}
</footer>


</html>

shift_maker/templates/shift_maker/createpage.html
{% extends 'shift_maker/base.html' %}
{% block body-contents %}

<p><a href="{% url 'shift_maker:shift_create_form_template' %}">テンプレートからシフトを募集</a></p>
<p><a href="{% url 'shift_maker:createslot' %}">新規スロットを作成</a></p>
<p><a href="{% url 'shift_maker:createshift' %}">シフトを募集</a></p>

{% endblock %}

shift_maker/templates/shift_maker/mypage.html
{% extends 'shift_maker/base.html' %}

{% block header %}
<h1>{{ user.account_name }}</h1>
{% endblock %}

{% block body-contents %}

<section class="section">
<u>
    <h2>今期の仕事量</h2>
    <h3>{{user.workload_sum}}</h3>
</u>

    <h2>{{ user.account_name }}さんが入るシフト枠</h2>
    <div class="container-fluid">
    <div class="row flex-row flex-nowrap overflow-auto">
    {% for slot in decided_assign_slot %}
    <div class="col-5">
        <div class="card card-block h-100">
          <div class="card-body">
            <h4 class="card-title">{{ slot.workname }}</h4>
            <p class="card-text">{{slot.day|date:'Y年n月j日'}}</p>
            <p class="card-text">{{slot.start_time|date:'G時i分'}}開始</p>
            <button type="button" class="btn btn-primary delete-modal-button"
    data-toggle="modal"
    data-target="#exampleModal"
    data-slotname="{{slot.workname}}"
    data-url="{% url 'shift_maker:slot_delete' slot.id %}"
    data-slot_day="{{slot.day|date:'Y年n月j日'}}"
    data-slot_starttime="{{slot.start_time|date:'G時i分'}}"
    data-slot_endtime="{{slot.end_time|date:'G時i分'}}"
    data-submitval="シフトをキャンセル"
    data-slot_content="{{slot.content.contentname}}">詳細</button>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    </div>

</section>

<section class="section">
<h2>{{ user.account_name }}さんが回答したシフト枠</h2>
<div class="container-fluid">
    <div class="row flex-row flex-nowrap overflow-auto">
    {% for slot in undecided_assign_slot %}
    <div class="col-5">
        <div class="card card-block h-100">
          <div class="card-body">
            <h4 class="card-title">{{ slot.workname }}</h4>
            <p class="card-text">{{slot.day|date:'Y年n月j日'}}</p>
            <p class="card-text">{{slot.start_time|date:'G時i分'}}開始</p>
            <button type="button" class="btn btn-primary delete-modal-button"
    data-toggle="modal"
    data-target="#exampleModal"
    data-slotname="{{slot.workname}}"
    data-url="{% url 'shift_maker:booking_slot_delete' slot.id %}"
    data-slot_day="{{slot.day|date:'Y年n月j日'}}"
    data-slot_starttime="{{slot.start_time|date:'G時i分'}}"
    data-slot_endtime="{{slot.end_time|date:'G時i分'}}"
    data-submitval="シフトをキャンセル"
    data-slot_content="{{slot.content.contentname}}">詳細</button>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    </div>
</section>

<section class="section">
<h2>人数が不足中のシフト枠</h2>
<div class="container-fluid">
    <div class="row flex-row flex-nowrap overflow-auto">
    {% for slot in lack_slot%}
    <div class="col-5">
        <div class="card card-block h-100">
          <div class="card-body">
            <h4 class="card-title">{{ slot.workname }}</h4>
            <p class="card-text">{{slot.day|date:'Y年n月j日'}}</p>
            <p class="card-text">{{slot.start_time|date:'G時i分'}}開始</p>
            <button type="button" class="btn btn-primary delete-modal-button"
    data-toggle="modal"
    data-target="#exampleModal"
    data-slotname="{{slot.workname}}"
    data-url="{% url 'shift_maker:assign_lack' slot.id %}"
    data-slot_day="{{slot.day|date:'Y年n月j日'}}"
    data-slot_starttime="{{slot.start_time|date:'G時i分'}}"
    data-slot_endtime="{{slot.end_time|date:'G時i分'}}"
    data-submitval="シフトを入れる"
    data-slot_content="{{slot.content.contentname}}">詳細</button>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
    </div>
</section>
<!--
<ul>
    <h2>応募したスロット</h2>
    {% for slot in undecided_assign_slot %}
        <li>{{ slot.workname }}</li>
        <button type="button" class="button is-danger delete-modal-button" data-toggle="modal" data-target="#decidedModal"
    data-slot_name="{{slot.workname}}"data-slot-day="{{slot.day}}" data-slot-starttime="{{slot.start_time}}"
    data-slot-endtime="{{slot.end_time}}" data-slot-content="{{slot.content.contentname}}"
    data-url="{% url 'shift_maker:booking_slot_delete' slot.id %}">ボタンで開く</button>
    {% endfor %}
</ul>
<ul>
    <h2>人数不足のスロット</h2>
    {% for slot in lack_slot %}
    <li><a href=>{{ slot.workname }}</a></li>
    <li>{{slot.required_number|add:slot.assigning_number}}</li>
    <button type="button" class="button is-danger delete-modal-button" data-toggle="modal" data-target="#decidedModal"
    data-slot_name="{{slot.workname}}"data-slot-day="{{slot.day}}" data-slot-starttime="{{slot.start_time}}"
    data-slot-endtime="{{slot.end_time}}" data-slot-content="{{slot.content.contentname}}"
    data-url="{% url 'shift_maker:assign_lack' slot.id %}">ボタンで開く</button>
    {% endfor %}
</ul>
-->
<h2>あなたが回答すべきシフト</h2>
<ul>
    {%for shift in shifts%}
    <li><a href="{% url 'shift_maker:recruit' shift.id %}">{{shift.shift_name}}</a></li>
    {% endfor %}
</ul>

<h2>決定済みのシフト</h2>
<ul>
    {%for shift in decided_shifts%}
    <li><a href="{% url 'shift_maker:result_schedule' shift.id %}">{{shift.shift_name}}</a></li>
    {% endfor %}
</ul>


<h2>{{user.account_name}}さんが募集をかけたシフト</h2>
<ul>
    {%for shift in made_shifts%}
    <li><a href="{% url 'shift_maker:recruit_detail' shift.id %}">{{shift.shift_name}}</a></li>
    {% endfor %}
    <a href="{% url 'shift_maker:create_page' %}">＋新しく募集する</a>
</ul>

<h2>他の人が募集をかけたシフト</h2>
<ul>
    {%for shift in others_shifts%}
    <li><a href="{% url 'shift_maker:recruit_detail' shift.id %}">{{shift.shift_name}}</a></li>
    {% endfor %}
</ul>

<ul>
    <a href="{% url 'shift_maker:password_change' %}">パスワードの変更</a>
</ul>


<div class="modal" style="z-index: 1500" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-background"></div>
        <div class="modal-card">
            <header class="modal-card-head">
                <p class="modal-card-title">確認</p>
            </header>
            <section class="modal-card-body">
                <div class="modal-body">
                    <p>仕事名　<span id="slotname"></span></p>
                    <p>日付　<span id="slot_day"></span></p>
                    <p>開始時刻　<span id="slot_starttime"></span></p>
                    <p>終了時刻　<span id="slot_endtime"></span></p>
                    <p>仕事内容　<span id="slot_content"></span></p>
                </div>
                </section>
            <footer class="modal-card-foot">
                <form action="" method="post" id="delete-form">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                    <button id="submit" type="submit" class="btn btn-primary">登録解除</button>
                </form>
            </footer>
        </div>
</div>




{% endblock %}

{% block footer %}
<a href="{% url 'shift_maker:logout' %}">ログアウト</a>
{% endblock %}

{% block extrajs %}
<script>$('#exampleModal').on('show.bs.modal', function (event) {
    //モーダルを開いたボタンを取得
    var button = $(event.relatedTarget)
    var watasuVal = button.data('slotname')
    var watasuVal2 = button.data('slot_day')
    var watasuVal3 = button.data('slot_starttime')
    var watasuVal4 = button.data('slot_endtime')
    var watasuVal5 = button.data('slot_content')
    var button_val=button.data('submitval')
    //モーダルを取得
    var modal = $(this)

    //受け取った値をspanタグのとこに表示
    modal.find('.modal-body span#slotname').text(watasuVal)
    modal.find('.modal-body span#slot_day').text(watasuVal2)
    modal.find('.modal-body span#slot_starttime').text(watasuVal3)
    modal.find('.modal-body span#slot_endtime').text(watasuVal4)
    modal.find('.modal-body span#slot_content').text(watasuVal5)
    modal.find('.modal-card-foot button#submit').text(button_val)
});

</script>
<script>

    const deleteForm = document.getElementById('delete-form');
    const modal = document.getElementById('exampleModal');
    const deleteModalButtons = document.getElementsByClassName('delete-modal-button');

    if (modal == null) {console.log('modal')};
    if (deleteModalButtons == null) {console.log('deleteModalButtons')};

    for (const button of deleteModalButtons) {
        button.addEventListener('click', () => {
            deleteForm.action = button.dataset.url;
        });


    }
</script>

{% endblock %}